---
#
# Configure td-agent from YUM repository.
#
# @see http://docs.fluentd.org/articles/install-by-rpm
# @see http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh
#

- name: add GPG key from Treasure Data, Inc
  command: rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent

- name: add official repository
  template:
    src: td.repo.j2
    dest: /etc/yum.repos.d/td.repo

- name: install td-agent
  yum: name=td-agent update_cache=yes state=present
  when: tdagent_version is not defined

- name: install td-agent
  yum: name="td-agent-{{ tdagent_version }}*" update_cache=yes state=present
  when: tdagent_version is defined
