---
# file: tasks/use-yum.yml
#
# Configure td-agent from YUM repository.
#

- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present

- name: amz-linux 2018.03
  include: use-yum-amz-linux-2018.03.yml
  when: ansible_distribution_version == '2018.03'

- name: all other amz-linux/redhat
  include: use-yum-common.yml
  when: ansible_distribution_version != '2018.03'

- name: install gcc and libcurlXXX for compiling plugins
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - libcurl
    - libcurl-devel
  when: tdagent_plugins is defined or tdagent_plugins_versions is defined

- name: set INIT status and start
  service: name=td-agent state=started enabled=yes
  when: tdagent_use_service|bool

- name: set INIT status (SysV style)
  command: /sbin/chkconfig td-agent on
  when: not tdagent_use_service|bool
